"""initial_schema

Revision ID: 3f2814949674
Revises: 
Create Date: 2026-05-30 00:20:10.650499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2814949674'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beer_batches', 'skip_condition',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('beer_recipes', 'yeast_type')
    op.add_column('breweries', sa.Column('upgrade_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_brewery_cond_tanks_brewery_id'), 'brewery_cond_tanks', ['brewery_id'], unique=False)
    op.drop_constraint(None, 'brewery_cond_tanks', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_cond_tanks', 'breweries', ['brewery_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_brewery_fermenters_brewery_id'), 'brewery_fermenters', ['brewery_id'], unique=False)
    op.drop_constraint(None, 'brewery_fermenters', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_fermenters', 'breweries', ['brewery_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_brewery_kettles_brewery_id'), 'brewery_kettles', ['brewery_id'], unique=False)
    op.drop_constraint(None, 'brewery_kettles', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_kettles', 'breweries', ['brewery_id'], ['id'], ondelete='CASCADE')
    op.alter_column('game_states', 'game_over',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('game_states', 'has_insurance',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_states', 'has_insurance',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('game_states', 'game_over',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'brewery_kettles', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_kettles', 'breweries', ['brewery_id'], ['id'])
    op.drop_index(op.f('ix_brewery_kettles_brewery_id'), table_name='brewery_kettles')
    op.drop_constraint(None, 'brewery_fermenters', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_fermenters', 'breweries', ['brewery_id'], ['id'])
    op.drop_index(op.f('ix_brewery_fermenters_brewery_id'), table_name='brewery_fermenters')
    op.drop_constraint(None, 'brewery_cond_tanks', type_='foreignkey')
    op.create_foreign_key(None, 'brewery_cond_tanks', 'breweries', ['brewery_id'], ['id'])
    op.drop_index(op.f('ix_brewery_cond_tanks_brewery_id'), table_name='brewery_cond_tanks')
    op.drop_column('breweries', 'upgrade_count')
    op.add_column('beer_recipes', sa.Column('yeast_type', sa.VARCHAR(), nullable=True))
    op.alter_column('beer_batches', 'skip_condition',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
